---
name: pr/check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: read-all
concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  trunk_check:
    name: Trunk Code Quality Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: trunk check
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: install mise
        # yamllint disable-line rule:line-length
        uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: true
          cache: true
      - name: build
        run: mise run build
      - name: unit tests
        run: mise run test
      - name: configure git for integration tests
        run: |
          git config --global user.email "ci@test.com"
          git config --global user.name "CI"
      - name: integration tests
        run: mise run test-integration
