---
name: release/release
on:
  push:
    tags:
      - v*
permissions: read-all
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - name: Generate GitHub token
        # https://github.com/actions/create-github-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: install mise
        # yamllint disable-line rule:line-length
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install: true
          cache: true
      - name: goreleaser
        run: mise x -- goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
