---
name: trunk upgrade
on:
  schedule:
    - cron: 0 16 * * 2 # At 16:00 on Tuesday
  workflow_dispatch: {}
permissions: read-all
jobs:
  trunk_upgrade:
    name: run trunk upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Generate GitHub token
        # https://github.com/actions/create-github-app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write
      - name: Trunk Upgrade
        # yamllint disable-line rule:line-length
        uses: trunk-io/trunk-action/upgrade@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          prefix: "chore: "
          lowercase-title: true
          sign-commits: true
